version: '3'

services:
  refresharr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: refresharr
    ports:
      - "9705:9705"
    volumes:
      - /docker:/config
      - /docker/refresharr-logs:/tmp/refresharr-logs
      - /docker/refresharr-state:/tmp/refresharr-state
    environment:
      TZ: America/New_York
      API_KEY: "bec5c5cbdef2428ab55ff644ba6ec6b9"
      API_URL: "http://192.168.1.188:8989/sonarr"
      API_TIMEOUT: "60"
      MONITORED_ONLY: "true"
      HUNT_MISSING_SHOWS: "1"
      HUNT_UPGRADE_EPISODES: "0"
      SLEEP_DURATION: "900"
      STATE_RESET_INTERVAL_HOURS: "168"
      DEBUG_MODE: "false"
      ENABLE_WEB_UI: "true"
      SKIP_FUTURE_EPISODES: "true"
      SKIP_SERIES_REFRESH: "false"
      COMMAND_WAIT_DELAY: "1"
      COMMAND_WAIT_ATTEMPTS: "600"
      MINIMUM_DOWNLOAD_QUEUE_SIZE: "-1"
      RANDOM_MISSING: "true"
      RANDOM_UPGRADES: "false"
    restart: unless-stopped
